# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mern-employer-app

on:
  push:
    branches: [ main]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step 0 : Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 1: Install dependencies and build the React app
      - name: Install dependencies and build client
        run: |
          npm install
          npm run build
        working-directory: mern/client

      # Step 2: Install server dependencies
      - name: Install server dependencies
        run: |
          npm install
        working-directory: mern/server

      # Step 3: Zip the entire server directory along with the built React app
      - name: Zip artifact for deployment
        run: |
          cp -r ../client/dist .
          zip -r release.zip .
        working-directory: mern/server

      # Step 4: Upload the artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: mern-app
          path: mern/server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: mern-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4506E0218F124078A602D8C2332D2C17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B38A9FC988E4EBDA1AD8D7F80CCED47 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B26E722AE7BE4751B016434B251D1577 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mern-employer-app'
          slot-name: 'Production'
          package: .
          